# 工作流名称
name: Update Tracker List for YogaDNS

# 触发条件
on:
  schedule:
    # 北京时间每周一、四 13:00（UTC 05:00）
    - cron: '0 5 * * 1,4'
  workflow_dispatch:  # 手动触发按钮

# 最小权限：仅允许创建 Release，其余只读
permissions:
  contents: write
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 拉取源码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 安装 Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 生成 YogaDNS 规则文件（含长度排序）
      - name: Generate yogadns_hosts.txt
        run: python src/convert_to_yogadns.py

      # 上传为 Actions 构件，供手动下载
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: yogadns_hosts
          path: output/yogadns_hosts.txt

      # 发布 GitHub Release（需 contents: write 权限）
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ github.run_number }}"  # 自动递增版本号
          name: "Tracker list build ${{ github.run_number }}"
          body: "自动生成，每周两次更新。"
          artifacts: "output/yogadns_hosts.txt"
          token: ${{ github.token }}  # 默认 GITHUB_TOKEN
          allowUpdates: true  # 若 tag 已存在则覆盖
